import React from 'react';
import ReactDOM from 'react-dom';
import Slider from './Slider';

const App = React.createClass({
	getInitialState: function() {
		return {
			red: 0,
			green: 0,
			blue: 0
		};
	},

	render: function() {
		return (
			<div>
				<Slider ref="red" update={this.updateStateTxt}/>
				{this.state.red}
				<br/>
				<Slider ref="green" update={this.updateStateTxt}/>
				{this.state.green}
				<br/>
				<Slider ref="blue" update={this.updateStateTxt}/>
				{this.state.blue}
				<br/>
			</div>
		);
	},

	propTypes: {
		txt: React.PropTypes.string,
		cat: React.PropTypes.number.isRequired
	},

	getDefaultProps: function() {
		return {
			txt: "this is the default txt"
		};
	},

	updateStateTxt: function(e){
		this.setState({
			//refs. only return the top level HTML element generated by the component
			//so if our Slider returns the input element inside a div element, the this.refs.red will return the div, in this case, you should
			//1. put the ref attribute for the input element created by the Slider component
			//2. using ReactDOM.findDOMNode(this.refs.red.refs.<ref_attr>)
			red: ReactDOM.findDOMNode(this.refs.red).value,
			green: ReactDOM.findDOMNode(this.refs.green).value,
			blue: ReactDOM.findDOMNode(this.refs.blue).value
		})
	}
});

export default App;